### ISSUE TITLE
HMAC Encoding Error

### ISSUE THREAD

**Issue by harehimself** [abrihter/duxwrap#3]
Hello,

I have encountered a consistent encoding error when attempting to create the HMAC Headers. 

File "C:\Python\lib\site-packages\duxwrap\duxwrap.py", line 101, in _create_signature
    message = bytes(data, 'ascii')
TypeError: encoding without a string argument

I have included my code (attached) for review.
[using-duxwrap-wrapper.txt](https://github.com/abrihter/duxwrap/files/9929833/using-duxwrap-wrapper.txt)

**Comment by abrihter** [comment]
@harehimself 
Hi
I do not have access to DW anymore, but I assume it should work if you remove line 41 completely 

`"targeturl": "{'https://app.dux-soup.com/xapi/remote/control/'}/{USER_ID}/queue",`
